version: 2
updates:
- package-ecosystem: gradle
  directory: /
  schedule:
    # Defaults to Monday 5am UTC.
    interval: weekly
  open-pull-requests-limit: 20
  reviewers:
  - glen-wiltshire-bsl
  - michael-lyndon-bsl
  labels:
  - dependencies
