##
 # Created by brightSPARK Labs
 # www.brightsparklabs.com
 ##

language: java

jdk:
  - openjdk11

notifications:
  email:
    on_success: never
    recipients:
      - support.insilico@brightsparklabs.com

# cache dependencies to speed up builds
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

jobs:
  include:
    - stage: unit tests
      script: ./gradlew build
    - stage: publish
      if: branch = master
      script: ./gradlew -i publishToMavenCentral
