##
 # Created by brightSPARK Labs
 # www.brightsparklabs.com
 ##

language: java

jdk:
  - openjdk8

sudo: false

notifications:
  email:
    on_success: never
    recipients:
      - support.insilico@brightsparklabs.com

# there is no signatory on build server, so exclude the 'signArchives' task
install:
  - ./gradlew assemble -x signArchives

# cache dependencies to speed up builds
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

