language: java

jdk:
  - oraclejdk7
  - oraclejdk8

sudo: false

notifications:
  email:
    on_success: never

# there is no signatory on build server, so call 'gradle jar' rather than
# 'gradle assemble' to prevent 'signArchives' from being called
install:
  - gradle jar
