##
 # Workflow for publishing the `master` branch to Maven Central after tests
 # succeed.
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

 name: Publish to Maven Central
 on:
   # Call workflow on push to the `master` branch.
   push:
     branches:
       - master
 
 jobs:
   call-test-workflow:
     uses: ./.github/workflows/test.yml
   call-publish-to-maven-central-workflow:
     # Specify that this job should only run if the test job succeeds.
     # See https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
     needs: call-test-workflow
     uses: brightsparklabs/github-actions/.github/workflows/publish-to-maven-central.yml@0.1.0
     with:
       github-ref-name: ${GITHUB_REF_NAME}
    # Since all of our workflows are called from the same organisation, we can use the `inherit`
    # keyword to pass secrets to the called workflow.
    # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit
     secrets: inherit
 