##
 # Workflow for running tests when changes are pushed.
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Test Pushed Changes
on:
  # Call workflow on push to any branch that's not the `master` branch.
  # Tests are run for the `master` branch in the `publish.yml` workflow.
  push:
    branches-ignore:
      - 'master'

jobs:
  call-test-workflow:
    # Run tests for non-Dependabot changes.
    # Tests are run for Dependabot changes in the `dependabot-test-and-auto-merge.yml` workflow.
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/test.yml
