##
 # A workflow for testing for breaking changes.
 #
 # This workflow can be called from workflows in this repo with:
 # ```
 # jobs:
 #   <job-id>:
 #     uses: ./.github/workflows/test.yml
 # ```
 #
 # See https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Test
on:
  # Call workflow on push.
  push:
  # Call workflow when called from other workflows.
  workflow_call:

jobs:
  call-test-gradle-build-workflow:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    uses: brightsparklabs/github-actions/.github/workflows/test-gradle-build.yml@0.1.0
    with:
      github-ref-name: ${GITHUB_REF_NAME}
      os: ${{ matrix.os }}
