##
 # Workflow to automate testing, dependency patching, and release publishing.
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Workflow
on: [push, pull_request]

jobs:
  # Run tests.
  call-test-gradle-build-workflow:
    # Prevent unnecessary duplicate test runs.
    if: |
      (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]')
    strategy:
      matrix:
        # Tests for Asanti are run on both Ubuntu and Windows.
        os:
          - ubuntu-latest
          - windows-latest
    uses: brightsparklabs/github-actions/.github/workflows/test-gradle-build.yml@0.1.0
    with:
      github-ref-name: ${GITHUB_REF_NAME}
      os: ${{ matrix.os }}
  # Auto-merge Dependabot PRs for patch and minor updates.
  call-dependabot-auto-merge-workflow:
    if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
    # Specify that this job should only run if the test job succeeds.
    needs: call-test-gradle-build-workflow
    # These permissions are required for Dependabot to merge the PR.
    permissions:
      contents: write
      pull-requests: write
    uses: brightsparklabs/github-actions/.github/workflows/dependabot-auto-merge.yml@0.1.0
    with:
      pr-url: ${{ github.event.pull_request.html_url }}
    # Since all of our workflows are called from the same organisation, we can use the `inherit`
    # keyword to pass secrets to the called workflow.
    secrets: inherit
  # Publish pushes to the `master` branch.
  call-publish-to-maven-central-workflow:
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    needs: call-test-gradle-build-workflow
    uses: brightsparklabs/github-actions/.github/workflows/publish-to-maven-central.yml@0.1.0
    with:
      github-ref-name: ${GITHUB_REF_NAME}
    secrets: inherit
